name: tagged-release

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build app
        run: |
          yarn install --frozen-lockfile
          yarn build
          cp config.example.js build
          pushd build
          zip -qr "../TileBoard.zip" .

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          file: TileBoard.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: Release ${{ github.ref }}
      
      - name: Copy README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: "addon/README.md"
      
      - name: Copy CHANGELOG.md
        uses: canastro/copy-file-action@master
        with:
          source: "CHANGELOG.md"
          target: "addon/CHANGELOG.md"

      - name: Update JSON version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: version
          VALUE: ${{ steps.get_version.outputs.VERSION }}
          FILE: addon/config.json

      - name: Update JSON image
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: image
          VALUE: ${{ secrets.DOCKER_USERNAME }}/tileboard-addon-{arch}
          FILE: addon/config.json

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ./addon \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}